#include <check.h>

#include "test_lifecycle/test_lifecycle.h"
#include "test_synchronization/test_barrier_based_matrix_sum/test_barrier_based_matrix_sum.h"
#include "test_synchronization/test_cigarette_smokers/test_cigarette_smokers.h"
#include "test_synchronization/test_coordinate_based_matrix_sum/test_coordinate_based_matrix_sum.h"
#include "test_synchronization/test_dining_savages/test_dining_savages.h"
#include "test_synchronization/test_fifo_barbershop/test_fifo_barbershop.h"
#include "test_synchronization/test_hilzers_barbershop/test_hilzers_barbershop.h"
#include "test_synchronization/test_linked_list/test_linked_list.h"
#include "test_synchronization/test_mutex_no_starve/test_mutex_no_starve.h"
#include "test_synchronization/test_queue/test_queue.h"
#include "test_synchronization/test_quicksort/test_quicksort.h"
#include "test_synchronization/test_random_barbershop/test_random_barbershop.h"
#include "test_synchronization/test_row_based_matrix_sum/test_row_based_matrix_sum.h"